### ISSUE TITLE
Lighten PendingProposals/ApprovedProposals/RejectedProposals query response

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#46]
The query response shows the payload of the proposals. It can be heavy if there is lot of proposals.
We should lighten this response so that instead of:
```
proposals:
- addAccountPayload:
    address: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
    coins:
    - amount: "10000000"
      denom: stake
    - amount: "1000"
      denom: token
  proposalInformation:
    chainID: my-chain
    createdAt: "1605688631"
    creator: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
    proposalID: 0
  proposalState:
    status: APPROVED
- addAccountPayload:
    address: cosmos14cuqsn9m7jf7ggzdpjmn9uanlsp5qa9xh4z24n
    coins:
    - amount: "10000000"
      denom: stake
    - amount: "1000"
      denom: token
  proposalInformation:
    chainID: my-chain
    createdAt: "1605688722"
    creator: cosmos14cuqsn9m7jf7ggzdpjmn9uanlsp5qa9xh4z24n
    proposalID: 1
  proposalState:
    status: APPROVED
- addValidatorPayload:
    genTx:
      auth_info:
        fee:
          amount: []
          gas_limit: "200000"
          granter: ""
          payer: ""
        signer_infos:
        - mode_info:
            single:
              mode: SIGN_MODE_DIRECT
          public_key:
            '@type': /cosmos.crypto.secp256k1.PubKey
            key: AwvYlRLgLjp2UCQYsyNxgwxMWL/YTIu45eUwvi4A1KD8
          sequence: "0"
      body:
        extension_options: []
        memo: 95a340e9cf7ee95c2970d95fd8f56348aa62398e@172.29.8.226:26656
        messages:
        - '@type': /cosmos.staking.v1beta1.MsgCreateValidator
          commission:
            max_change_rate: "0.010000000000000000"
            max_rate: "0.200000000000000000"
            rate: "0.100000000000000000"
          delegator_address: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
          description:
            details: ""
            identity: ""
            moniker: mynode
            security_contact: ""
            website: ""
          min_self_delegation: "1"
          pubkey: cosmosvalconspub1zcjduepq4z62c9xljkylkk2rptk787y9zf9pfhkrtve6tqldn25lymdlxfcqctj8yg
          validator_address: cosmosvaloper1ypjda55c40m3xwtjunc9yuwuxf06cjt9d0y6pg
          value:
            amount: "100000000"
            denom: stake
        non_critical_extension_options: []
        timeout_height: "0"
      signatures:
      - KKPMKVKu8aiW41K9VgA89ZgDaRrRKUzVd+ebco+ZSZ8zOZ/4IdYb9lTrS+dGZEcCl22Bdnnl613mHNdV9biH7Q==
    peer: peer.com
  proposalInformation:
    chainID: my-chain
    createdAt: "1605688804"
    creator: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
    proposalID: 2
  proposalState:
    status: APPROVED
```

We have:
```
 - proposalInformation:
    chainID: my-chain
    createdAt: "1605688631"
    creator: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
    proposalID: 0
  proposalState:
    status: APPROVED
  proposalType: "AddAccount"
- proposalInformation:
    chainID: my-chain
    createdAt: "1605688722"
    creator: cosmos14cuqsn9m7jf7ggzdpjmn9uanlsp5qa9xh4z24n
    proposalID: 1
  proposalState:
    status: APPROVED
  proposalType: "AddAccount"
- proposalInformation:
    chainID: my-chain
    createdAt: "1605688804"
    creator: cosmos1ypjda55c40m3xwtjunc9yuwuxf06cjt9gms0dm
    proposalID: 2
  proposalState:
    status: APPROVED
  proposalType: "AddValidator"
```

Then the user can get more details with the query `show-proposal`
