### ISSUE TITLE
Distributed rewards not balanced depending on relative signatures

### ISSUE THREAD

**Issue by lumtis** [tendermint/spn#513]
Depends on https://github.com/tendermint/spn/pull/506

**Describe the bug**
When the following `MonitoringPacket` is received on `spn`
```
spnd q monitoring-consumer list-monitoring-history

monitoringHistory:
- latestMonitoringPacket:
    blockHeight: "142"
    signatureCounts:
      blockCount: "100"
      counts:
      - RelativeSignatures: "32.999999999999999967"
        consAddress: 7hA1g2S4ulkRUmWYAoa2ukIYZUA=
      - RelativeSignatures: "32.999999999999999967"
        consAddress: iYH/hrUeZvFXtBpNe2UUBxiCdjw=
      - RelativeSignatures: "32.999999999999999967"
        consAddress: 4aI+0x4FyCcJ176uXMUBXhN7GIU=
  launchID: "1"
```

And the reward pool is:

```
rewardPool:
- coins:
  - amount: "50000"
    denom: v/1/orbit
  currentRewardHeight: "0"
  lastRewardHeight: "100"
  launchID: "1"
  provider: spn1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul
```

The distributed reward balances are 

```
spnd q bank balances spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
balances:
- amount: "100000000"
  denom: uspn
- amount: "3649"
  denom: v/1/orbit
spnd q bank balances spn1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5
balances:
- amount: "100000000"
  denom: uspn
- amount: "11055"
  denom: v/1/orbit
spnd q bank balances spn1twckcceyw43da9j247pfs3yhqsv25j38grh68q
balances:
- amount: "100000000"
  denom: uspn
- amount: "33500"
  denom: v/1/orbit
```

The balance of the reward `v/1/orbit` should be the same for all accounts since they all have the same value for `RelativeSignatures`

May be related to value of `blockHeight` that is above `lastBlockHeight` for the reward pool

**To Reproduce**

Follow the `Running an Incentivized Testnets` guide

**Comment by lubtd** [comment]
Balance of `Alice` (provider) is
```
balances:
- amount: "100000000"
  denom: uspn
- amount: "1796"
  denom: v/1/orbit
```

This should be almost `0` since all blocks are signed by all validators
