### ISSUE TITLE
Begin-blocker: skip block `1` for counting signatures

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#564]
We currently in the begin-blocker starting counting signature at height `1` for monitoring packet.

However, the first block is the genesis block and not signed by any validator in the validator set. This give a monitoring packet containing value like:
```
    blockCount: "60"
    counts:
    - RelativeSignatures: "19.666666666666666647"
      consAddress: iYH/hrUeZvFXtBpNe2UUBxiCdjw=
    - RelativeSignatures: "19.666666666666666647"
      consAddress: 4aI+0x4FyCcJ176uXMUBXhN7GIU=
    - RelativeSignatures: "19.666666666666666647"
      consAddress: 7hA1g2S4ulkRUmWYAoa2ukIYZUA=
```

If validators signed all blocks we should have
```
    blockCount: "60"
    counts:
    - RelativeSignatures: "20"
      consAddress: iYH/hrUeZvFXtBpNe2UUBxiCdjw=
    - RelativeSignatures: "20"
      consAddress: 4aI+0x4FyCcJ176uXMUBXhN7GIU=
    - RelativeSignatures: "20"
      consAddress: 7hA1g2S4ulkRUmWYAoa2ukIYZUA=
```

If should skip the first height in the Begin-Blocker
