### ISSUE TITLE
Make `list-auction-used-allocations` listing only the auction's used allocations for one user

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#681]
We want the query `list-auction-used-allocations` to list the auction's used allocations for one specific user (`list-used-allocations`) can be used to get all used allocations independently from the users

Currently, the CLI command take the address of the user but show all the auction's used allocations for all users:
```
spnd q participation list-auction-used-allocations -h
List all used allocations for auctions for an address

Usage:
  spnd query participation list-auction-used-allocations [address] [flags]
```
->
```
spnd q participation list-auction-used-allocations spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
auctionUsedAllocations:
- address: spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
  auctionID: "1"
  numAllocations: "10"
  withdrawn: true
- address: spn1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5
  auctionID: "1"
  numAllocations: "10"
  withdrawn: true
- address: spn1twckcceyw43da9j247pfs3yhqsv25j38grh68q
  auctionID: "1"
  numAllocations: "10"
  withdrawn: true
pagination:
  next_key: null
  total: "0"
```
