### ISSUE TITLE
Add metadata for `spn` in `bank`

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#761]
`atom` metadata on the hub:
```
metadatas:
- base: uatom
  denom_units:
  - aliases:
    - microatom
    denom: uatom
    exponent: 0
  - aliases:
    - milliatom
    denom: matom
    exponent: 3
  - aliases: []
    denom: atom
    exponent: 6
  description: The native staking token of the Cosmos Hub.
  display: atom
  name: ""
  symbol: ""
```

We should implement the same with `spn/mspn/uspn`
